name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
       username: deahox
       password: ${{ secrets.DOCKER_HUB_PASSWORD}}

    - name: Build the Docker image and push to Docker Hub
      working-directory: web-app
      env:
       IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build . --file Dockerfile --tag deahox/lab3-devops:$IMAGE_TAG
        docker push deahox/lab3-devops:$IMAGE_TAG

    
